version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ionic-native/splash-screen"
    versions:
    - 5.30.0
    - 5.31.1
    - 5.32.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.0.7
    - 11.1.4
    - 11.2.1
    - 11.2.4
    - 11.2.6
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: "@angular-devkit/architect"
    versions:
    - 0.1101.1
    - 0.1102.0
    - 0.1102.5
  - dependency-name: "@ionic-native/firebase-x"
    versions:
    - 5.31.1
  - dependency-name: "@ionic-native/core"
    versions:
    - 5.30.0
  - dependency-name: zone.js
    versions:
    - 0.11.3
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
